name: "Pointsman"
description: "Charge your home battery system depending on your dynamic tariff"
version: "16.3.1"
slug: "Pointsman"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/hassio-addons/base
