---
name: "Pointsman"
description: "Charge your home battery system depending on your dynamic tariff"
version: "0.0.2c"
slug: "Pointsman"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
