name: "Pointsman"
description: "Charge your home battery system depending on your dynamic tariff"
version: "0.0.2p"
slug: "pointsman"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8501/tcp: 8501
